SkyJSTranslationsLoaded({
    "btn_get_started" : "Get started",
    "btn_ok" : "OK",
    "btn_close" : "Close",
    "btn_continue" : "Continue",
    "lnk_start_call" : "Start call",
    "lnk_learn_more" : "Learn more about Skype",
    "lnk_learn_more_about_outlook" : "Learn more about Skype for Outlook.com",
    "lnk_learn_more_about_account_merging" : "Learn more about account merging",
    "lnk_get_skype" : "Get Skype",
    "msg_setup_info_in_title" : "{INVITER} wants to have a free Skype call with you.",
    "msg_setup_info_in" : "Download the Skype plugin with this quick, one-time setup so we can connect you.",
    "msg_setup_info_out" : "To call {INVITER}, you need to download the Skype plugin with this quick, one-time setup.",
    "msg_setting_up_info" : "Your download has started. Please follow the prompts to save and run the Skype plugin.",
    "msg_just_a_moment" : "Just a moment\u2026",
    "msg_click_save_file" : "Click 'Save File'",
    "msg_run_downloaded_file" : "Run the downloaded file",
    "msg_ready_to_start_calling" : "Ready to start calling",
    "msg_download_too_long" : "If your download is interrupted or taking too long, you can {LINK_RESTART_MANUALLY}restart it manually{LINK_END} or download the {LINK_GET_SKYPE_APP}full Skype app{LINK_END} now.",
    "msg_setup_complete" : "Your setup is complete. You are ready to start the call with {INVITER}",
    "msg_setup_complete_call_inviter" : "Setup is complete. You can call {INVITER} now.",
    "msg_enjoy_skype_call" : "Enjoy your Skype call with {INVITER}",
    "msg_invite_expired" : "Sorry, this call link has expired.",
    "msg_ask_for_link" : "Ask {INVITER} to call you again if you want a new link. Or download Skype to call them for free anytime you like.",
    "msg_cookies_disabled" : "Cookies are disabled",
    "msg_cookies_disabled_ext" : "Cookies are not enabled on your browser. To continue, change the appropriate setting in the security options.",
    "msg_install_plugin_outlook" : "Please install the Skype plugin to set up calling from Outlook.com",
    "msg_install_plugin_and_call_from_outlook" : "Please install the Skype plugin to set up calling from Outlook.com.",
    "msg_play_video" : "Play video",
    "msg_wrong_user" : "You\u2019re signed in as a different user",
    "msg_wrong_user_text" : "You\u2019ve received an invitation to make a call, but you\u2019re signed into a different Microsoft account than the one this invitation was intended for. To make this call either download Skype, or sign in using a different Microsoft account.",
    "ttl_skype_calling_setup" : "Skype calling setup",
    "lnk_tou_agree" : "I agree - continue",
    "lnk_tou_disagree" : "Not now, thanks",
    "msg_voice_and_video" : "Free voice and video calls",
    "msg_easily_ims" : "Send instant messages even on a call",
    "msg_call_your_buddies" : "Call all your Messenger contacts",
    "msg_bring_skype_contacts" : "Bring Skype contacts into Outlook.com",
    "msg_before_we_start" : "Before we start\u2026",
    "msg_you_must_agree" : "You must agree to the {LINK_TERMS}Skype Terms of Use{LINK_END} and {LINK_PRIVACY}Skype Privacy Policy{LINK_END}.",
    "msg_before_we_start_you_must_agree" : "Before we start, you must agree to the {LINK_TERMS}Skype Terms of Use{LINK_END} and {LINK_PRIVACY}Skype Privacy Policy{LINK_END}",
    "msg_inform_me_about_new_products" : "Inform me about new products, features, and special offers by email.",
    "msg_would_you_like_to_merge" : "Would you like to merge your Skype and Microsoft account so you\u2019ll see your Skype contacts in Outlook.com?",
    "msg_skype_account_to_merge" : "Enter your Skype account details",
    "alt_back" : "Back",
    "plh_skype_name" : "Skype Name",
    "plh_password" : "Password",
    "val_sign_in" : "Sign in",
    "lnk_problems_signing_in" : "Problems signing in?",
    "msg_reach_your_skype_contacts_in_outlook_and_call" : "You can now reach your Skype and Messenger contacts in Outlook.com.",
    "msg_can_not_connect_to_skype_server" : "Sorry, we can\u2019t connect to the Skype server. Try again later.",
    "ttl_age_limit" : "Sorry, an age limit applies",
    "txt_age_limit" : "You can\u2019t sign into Skype with this Microsoft account because you don\u2019t meet the age limit for your country.",
    "ttl_problem_signing_in" : "There was a problem signing in",
    "msg_problem_signing_in" : "You have tried to sign in unsuccessfully too many times. Please wait a minute then try again.",
    "ttl_not_signed_in" : "You are not signed into live.com",
    "msg_not_signed_in" : "You are currently not signed into live.com. Please sign in first and try again.",
    "lnk_cancel_and_change_account" : "Cancel and change account",
    "msg_check_your_details" : "Sorry, that didn\u2019t work. Check your details.",
    "msg_setup_is_complete_ready_to_calling" : "Setup is complete. You are ready to start calling.",
    "msg_how_to_make_a_call" : "How to make a call",
    "msg_click_on_chat_icon" : "Click on the chat icon in the top right corner",
    "msg_select_person_to_call" : "Select the person you want to call",
    "msg_click_on_video_or_voice_call_buttons" : "Click on the video or voice call buttons",
    "msg_need_more_help" : "Need more help?",
    "lnk_watch_this_video" : "Watch this video",
    "msg_accounts_is_already_merged" : "Account is already merged",
    "msg_account_is_already_merged" : "The Skype account {SKYPE_ACCOUNT} is already merged with another Microsoft account.",
    "msg_what_you_can_do" : "What you can do:",
    "msg_use_existing_merged_skype_account" : "Sign in to Outlook.com with a different Microsoft account.",
    "msg_merge_your_accounts" : "One last step - merge your accounts",
    "msg_merge_this_microsoft_account" : "{LINK_MERGE}Merge this Microsoft account{LINK_END} with a different Skype account.",
    "msg_create_a_brand_new_skype_account" : "{LINK_NEW_ACCOUNT}Create a brand new Skype account{LINK_END} (and then merge to this Microsoft account if you wish)",
    "lnk_get_more_help_with_account_merging" : "Get more help with account merging",
    "btn_i_have_skype_account" : "I have a Skype account",
    "btn_new_to_skype" : "No, I\u2019m new to Skype",
    "msg_generic_error" : "Oops, something went wrong",
    "msg_generic_error_text" : "Looks like Skype for Outlook.com is not available at the moment. Please try again later or download the full Skype app now.",
    "msg_rollback" : "Oops, something went wrong. Looks like Skype for Outlook.com is not available at the moment. Please try again later or download the full Skype app now.",
    "btn_download_skype" : "Download Skype",
    "ttl_metro_plugin_not_supported" : "Get Skype from the Store",
    "msg_metro_plugin_not_supported" : "Your version of Internet Explorer does not currently support the Skype for Outlook.com plugin. But worry not, we have a new, fast and beautiful Skype waiting for you in the Store. It\u2019s free too.",
    "msg_metro_plugin_not_supported_winrt" : "Your version of Windows does not currently support the Skype for Outlook.com plugin. But worry not, we have the new, fast and beautiful Skype waiting for you in the Store. It\u2019s free too.",
    "msg_skype_for_metro" : "Sorry, Skype for Outlook.com doesn\u2019t work with this browser. Please download the latest version of Skype for Windows 8 to get the best experience.",
    "btn_get_skype_for_metro" : "Get Skype for Windows RT",
    "ttl_skype_plugin_update" : "Your Skype plugin needs updating",
    "msg_skype_plugin_update" : "To make this Skype call, you\u2019ll need to update to the latest version.",
    "btn_update_plugin" : "Update plugin",
    "ttl_after_instalation_continue" : "After the installation is complete, click \"Continue\"",
    "ttl_heres_what_todo_next" : "Here\u2019s what to do next:",
    "msg_select_run" : "Select \"Run\"",
    "msg_your_skype_plugin_installs" : "Your Skype plugin installs",
    "msg_thats_it_start_calling" : "That\u2019s it - start calling",
    "ttl_your_skype_is_downloading" : "Your Skype plugin is downloading. It won\u2019t take long\u2026",
    "ttl_plugin_download_error" : "We couldn\u2019t download the Skype plugin for Outlook.com",
    "txt_ie10_window8_error" : "Internet Explorer 10 for Windows 8 doesn\u2019t currently support this plugin. But you can download the full Skype app from the Store.",
    "msg_reinstall_outgoing" : "To call {INVITER}, you need to update your Skype plugin. It won\u2019t take long.",
    "msg_reinstall_incoming" : "To speak with {INVITER}, you need to update your Skype plugin first. It won\u2019t take long.",
    "ttl_pluginInstall" : "Your download has started. What next?",
    "msg_pluginInstall_msie_step1" : "After it has downloaded, run the Skype plugin installer.",
    "msg_pluginInstall_msie_step2" : "Click \u201CYes\u201D to accept the User Account Control settings.",
    "msg_pluginInstall_chrome_win_step1" : "Run the Skype plugin installer \u2013 it\u2019s in the lower left corner of your browser.",
    "msg_pluginInstall_chrome_win_step2" : "Click \u201CYes\u201D to accept the User Account Control settings.",
    "msg_pluginInstall_firefox_win_step1" : "Click \u201CSave File\u201D when you\u2019re prompted.",
    "msg_pluginInstall_firefox_win_step2" : "Double-click \u201CSkypeWebPlugin.msi\u201D in the Downloads window.",
    "msg_pluginInstall_safari_step1" : "The Skype plugin will download to your computer.",
    "msg_pluginInstall_safari_step2" : "Run the downloaded file and follow the instructions.",
    "msg_pluginInstall_step3" : "You\u2019re ready to start calling.",
    "msg_setup_info_preview_title" : "Welcome. Preview Skype today.",
    "msg_skype_call" : "Skype call",
    "msg_plugin_not_installed_yet" : "It looks like the plugin isn't installed yet. Please follow these instructions.",
    "btn_next" : "Next",
    "msg_select_next_after_plugin_is_installed" : "Select \"Next\" after you've installed the plugin.",
    "btn_let_get_started" : "Let's get started",
    "msg_plugin_download_started" : "Your download has started.",
    "msg_select_next" : "Select \"Next\" after you've installed the plugin.",
    "btn_toast_answer_video" : "Start video call",
    "btn_toast_answer_audio" : "Start voice call",
    "btn_toast_decline" : "Decline call"
});